### ISSUE TITLE
Cells not cropped according to the CellIndex column

### ISSUE THREAD

**Issue by Calebium** [AllenCellModeling/actk#23]
## Description
*A clear description of the bug*

Individual cells in an FOV are cropped based on the CellIndex column in the metadata csv. However, the cropped image from the CellImage3DPath column appears to show a cell that is cropped not according to CellIndex.

## Expected Behavior
*What did you expect to happen instead?*

Cells should be cropped based on their CellIndex value.

## Reproduction
*A minimal example that exhibits the behavior.*

Below is a cell cropped from ACTK:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/8196285/89354453-bda97480-d66d-11ea-91ed-0083bd1e9e03.png">

This is different from the one cropped in the Quilt data set using the same segmentation file and CellIndex:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/8196285/89354509-e2055100-d66d-11ea-8ab8-32a6faa34d06.png">

This can be shown from the FOV image, where the cell circled in green is the cell that should be cropped, but instead, the cell circled in red is cropped in CellImage3DPath:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/8196285/89354603-1bd65780-d66e-11ea-869d-86e24352702e.png">

## Environment
*Any additional information about your environment*

**Comment by Calebium** [comment]
My initial analysis were performed using Jianxu's new test set, and the results from the ACTK output generated by Rory in:

`/allen/aics/modeling/rorydm/projects/actk/`

However, the same results can be reproduced using the following input csv with the same cell as I was describing above (I had to rename it to .txt for attachment):

[dfCSV_ACTK_M0_SingleObjs_Test.txt](https://github.com/AllenCellModeling/actk/files/5025340/dfCSV_ACTK_M0_SingleObjs_Test.txt)

I ran this single cell csv file using the following command and generate a log file:

`actk all run --dataset dfCSV_ACTK_M0_SingleObjs_Test.csv > dfCSV_ACTK_M0_SingleObjs_Test_`timestamp`.log 2>&1`

After the run, I opened the image in the CellImage3DPath using itkwidgets in Jupyter notebook and displayed the DNA channel (the first image above). I also opened the image in the SourceReadPath field to look at the FOV (DNA channel), which is the 3rd image above.

In order to confirm that the correct cell was cropped or not, I used 2 methods to verify:

(1) From the ACTK output csv I opened the nucleus segmentation image from the NucleusSegmentationReadPath field and display the cropped cell by doing:

`view((AICSImage(dfCSV_ACTKOut_Test['NucleusSegmentationReadPath'].iloc[0]).data[0, 0, 0, :, :, :] == dfCSV_ACTKOut_Test['CellIndex'].iloc[0] * 1).astype(np.uint16))`

Where dfCSV_ACTKOut_Test is the dataframe of the ACTK output csv. By doing this, I saw that the cell selected in the nucleus segmentation is not the same one as I saw in the first image above. If I hardcode the CellIndex value to 4 (instead of 1 for this cell), then I do get the same nucleus as I see in the first image.

(2) With Jianxu's help I was able to cross reference most of the cells in this data set to the one in the 3D trained model. I won't go into the details here but for this particular cell, the old cell index was 65175, and so I opened the 3D trained model's input images for examination at:

`/allen/aics/modeling/gregj/results/ipp/scp_19_04_10/plate_3500001657/16401_65175_reg.tiff`

Note that the CellId is in the filename, so if the cross referencing code is correct, this should be the file of the same cell that was used for the model training. With this, I simply viewed the image's DNA channel, which gave me the second image I posted above.

So at this point I noticed that the two images are not the same. However, if I look at the FOV (third) image, I was able to identify the ACTK cropped nucleus (first image) as the one in the red circle in the FOV, and the image used by the 3D model (second image) is the one in the green circle. So my conclusion is that the FOV used in both cases are the same, the only difference is that two different neighboring nuclei were cropped.

And the reason I tend to think that ACTK was not cropping the intended nucleus was because of method (1), if I mask the nucleus segmentation using CellIndex = 1 (the correct index) I get the same nucleus as that in the second image, but if I use CellIndex = 4 (I tried 2 and 3 first), then I get the nucleus cropped bu ACTK.

I apologize the the long description, I hope this is more helpful. But I'm ready to talk any time and provide any more info that is required.

Thanks!

**Comment by donovanr** [comment]
Hi Caleb, thanks for the details but I still think I'm unclear about a lot of what's going  on here.  That is, I understand there's a mismatch, but I'm still not sure which data sets it's between, or if it's to be expected or not.  Maybe we can talk this afternoon or on Thursday.
